//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Action { get; set; }
        public int PrinterId { get; set; }
        public string PrinterModel { get; set; }
        public string PrinterName { get; set; }
        public string PrinterLocation { get; set; }
        public string PrinterOwner { get; set; }
        public string PrinterComment { get; set; }
        public int SupplyId { get; set; }
        public string SupplyPartNumber { get; set; }
        public string SupplyName { get; set; }
        public string SupplyComment { get; set; }
    }
}
